# Generated by Django 4.0.4 on 2022-05-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_caption_video_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='media/%y'),
        ),
    ]
